// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { Counter, CounterTableId } from "./tables/Counter.sol";
import { Position, PositionData, PositionTableId } from "./tables/Position.sol";
import { EntityType, EntityTypeTableId } from "./tables/EntityType.sol";
import { OwnedBy, OwnedByTableId } from "./tables/OwnedBy.sol";
