name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: Run Type Check, Linters
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      # pnpm no longer runs this before the actual install (https://github.com/pnpm/pnpm/issues/3760)
      # but we need to create some placeholder files like bins so that the install step can find them and put references to them in the right spot
      # this resolves some chicken-and-egg problems with using workspace bins before they're created (install -> build -> install)
      - name: Run prepare scripts
        shell: bash
        run: pnpm recursive run prepare

      - name: Install node dependencies
        shell: bash
        run: pnpm install --frozen-lockfile

      # Workaround for parallel building with forge:
      # https://github.com/foundry-rs/foundry/issues/4736
      - name: Setup forge
        shell: bash
        working-directory: packages/schema-type
        run: forge build

      - name: Cache turbo build
        uses: actions/cache@v3
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.ref_name }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-${{ github.ref_name }}-
            ${{ runner.os }}-turbo-main-
            ${{ runner.os }}-turbo-

      - name: Build
        shell: bash
        run: pnpm turbo run build --cache-dir=.turbo --concurrency 10

      - name: Outdated files, run `pnpm build` and commit them
        uses: ./.github/actions/require-empty-diff

      - name: Check types
        run: pnpm run type-check
        if: always()

      - name: Check linting
        run: pnpm run lint
        if: always()

      - name: Check commits messages
        uses: wagoid/commitlint-github-action@v5
        if: always()
