name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: Run Type Check, Linters
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      # pnpm no longer runs this before the actual install (https://github.com/pnpm/pnpm/issues/3760)
      # but we need to create some placeholder files like bins so that the install step can find them and put references to them in the right spot
      # this resolves some chicken-and-egg problems with using workspace bins before they're created (install -> build -> install)
      - name: Run prepare scripts
        shell: bash
        run: pnpm recursive run prepare

      - name: Install node dependencies
        shell: bash
        run: pnpm install --frozen-lockfile

      - name: Build
        shell: bash
        run: pnpm recursive run build

      - name: Check types
        run: pnpm run type-check
        if: always()

      - name: Check linting
        run: pnpm run lint
        if: always()

      - name: Check commits messages
        uses: wagoid/commitlint-github-action@v5
        if: always()
